// Builds the bead click samples from the recordings in audio-src/ (see audio-src/SOURCES.md).
// Run: npm run build:clicks   →   writes src/clicks.data.js and audio-src/preview.wav
//
// For each material: find every click in its recordings, keep the clean ones (well above
// the sound just before them, no second click crowding them, loud enough), pick a varied
// set, then cut each one (2 ms before the hit, at most 120 ms long, faded out), remove
// rumble below 80 Hz, and level them so every material plays at the same loudness.
import { writeFileSync } from 'fs';
import { decode, findClicks, measure, setRate } from './lib/clicks.mjs';

const SR = 32000;   // stored sample rate: keeps the brightness of the clicks, half the size of 44.1 kHz 16-bit
setRate(SR);
const MATERIALS = {
  amber: { files: ['347928-rosary.mp3'], count: 10 },                                // light, bright: resin
  olive: { files: ['614852-wooden-bracelet.mp3'], count: 10 },                     // wooden beads
  ebony: { files: ['174216-abacus-hard.mp3', '863239-abacus.mp3'], count: 7 },      // dense, hard wood
};
const MAX_LEN = 0.12, FADE = 0.03, TARGET_RMS = 0.18;
const dir = new URL('../audio-src/', import.meta.url).pathname;

const out = { sampleRate: SR }, report = [], previewParts = [];
for (const [mat, spec] of Object.entries(MATERIALS)) {
  const candidates = [];
  for (const f of spec.files) {
    const x = decode(dir + f), on = findClicks(x);
    on.forEach((a, i) => { const m = measure(x, a, on[i + 1]); if (m.isolationDb > 15 && !m.crowded && m.peakDb > -40) candidates.push({ ...m, x, file: f }); });
  }
  // the cleanest first; then spread across brightness so the set doesn't sound alike
  candidates.sort((p, q) => q.isolationDb - p.isolationDb);
  const pool = candidates.slice(0, Math.max(spec.count * 2, spec.count));
  pool.sort((p, q) => p.centroid - q.centroid);
  const picked = Array.from({ length: Math.min(spec.count, pool.length) }, (_, i) => pool[Math.round(i * (pool.length - 1) / Math.max(1, spec.count - 1))]);
  out[mat] = picked.map(c => {
    const len = Math.round(SR * MAX_LEN), y = new Float32Array(len);
    for (let i = 0; i < len && c.start + i < c.x.length; i++) y[i] = c.x[c.start + i];
    // rumble out: a gentle one-pole high-pass at 80 Hz
    const a = Math.exp(-2 * Math.PI * 80 / SR); let px = 0, py = 0;
    for (let i = 0; i < len; i++) { const v = y[i]; py = a * (py + v - px); px = v; y[i] = py; }
    // fades: 0.5 ms in, FADE out
    const fi = Math.round(SR * 0.0005), fo = Math.round(SR * FADE);
    for (let i = 0; i < fi; i++) y[i] *= i / fi;
    for (let i = 0; i < fo; i++) y[len - 1 - i] *= i / fo;
    // level: the loudness of the first 30 ms, so every material clicks equally loud
    let s = 0; const w = Math.round(SR * 0.03); for (let i = 0; i < w; i++) s += y[i] * y[i];
    const g = TARGET_RMS / Math.sqrt(s / w); let peak = 0;
    for (let i = 0; i < len; i++) { y[i] *= g; peak = Math.max(peak, Math.abs(y[i])); }
    if (peak > 0.95) for (let i = 0; i < len; i++) y[i] *= 0.95 / peak;   // never clip
    previewParts.push(y, new Float32Array(Math.round(SR * 0.18)));
    report.push(`${mat.padEnd(6)} ${c.file.padEnd(28)} at ${(c.start / SR).toFixed(3)} s  isolation ${c.isolationDb} dB  centroid ${c.centroid} Hz`);
    const pcm = new Int16Array(len); for (let i = 0; i < len; i++) pcm[i] = Math.round(Math.max(-1, Math.min(1, y[i])) * 32767);
    return Buffer.from(pcm.buffer).toString('base64');
  });
  previewParts.push(new Float32Array(Math.round(SR * 0.6)));
}

const sources = report.map(r => '//   ' + r).join('\n');
writeFileSync(new URL('../src/clicks.data.js', import.meta.url), `// Generated by \`npm run build:clicks\` from the recordings in audio-src/ (credits in
// audio-src/SOURCES.md). 16-bit mono PCM, base64, at ${SR} Hz; one entry per click.
${sources}
export const CLICKS = ${JSON.stringify(out)};
`);
// a listening file: every chosen click, material by material
const total = previewParts.reduce((n, p) => n + p.length, 0), wav = Buffer.alloc(44 + total * 2);
wav.write('RIFF', 0); wav.writeUInt32LE(36 + total * 2, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22);
wav.writeUInt32LE(SR, 24); wav.writeUInt32LE(SR * 2, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(total * 2, 40);
let o = 44; for (const p of previewParts) for (const v of p) { wav.writeInt16LE(Math.round(Math.max(-1, Math.min(1, v)) * 32767), o); o += 2; }
writeFileSync(dir + 'preview.wav', wav);
console.log(report.join('\n'));
console.log(`\nsrc/clicks.data.js: ${Object.entries(out).filter(([k]) => k !== 'sampleRate').map(([k, v]) => `${k} ${v.length}`).join(', ')}; ${(JSON.stringify(out).length / 1024).toFixed(0)} kB`);
