// White balance: finds the lamp colour temperature at which undyed ivory wool, lit at the
// centre of the lamp's pool, reads as ivory with only a trace of warmth, just as a
// photographer sets a camera's white balance to the light. The material colours stay
// their true daylight values; only the light is calibrated.
// Run with the dev server up: npm run calibrate:colour  (then npm run verify:colour)
import { writeFileSync } from 'fs';
import { WHITE_REF, kelvinToHex, labToHex, labToLch, lchToLab } from '../src/palette.js';
import { launch, open, probePoint, surfaceColours } from './lib/render.mjs';

// the lamp should add a trace of warmth on top of the wool's own colour: this much on
// OKLab's b axis (yellow–blue), about a third of the way from neutral to the beads' amber
const ADDED_WARMTH = 0.025;
const browser = await launch();
const page = await open(browser, 'amber', 'hold');
const point = await probePoint(page, 'rug');
const WARMTH = lchToLab(WHITE_REF)[2] + ADDED_WARMTH;

async function ivoryAt(k) {
  const hex = kelvinToHex(k);
  await page.evaluate(hex => { __stage.lamp.color.set(hex); __stage.glow.color.set(hex); }, hex);
  return (await surfaceColours(page, 'rug', { ref: labToHex(lchToLab(WHITE_REF)) }, point)).ref;
}

// warmer light → more yellow ivory, so bisect on the temperature
let lo = 2000, hi = 9000;
for (let i = 0; i < 18; i++) {
  const mid = (lo + hi) / 2, b = (await ivoryAt(mid))[2];
  if (b > WARMTH) lo = mid; else hi = mid;
}
const kelvin = Math.round((lo + hi) / 2 / 50) * 50;
const seen = labToLch(await ivoryAt(kelvin));
await browser.close();

writeFileSync(new URL('../src/palette.calibrated.js', import.meta.url), `// Generated by \`npm run calibrate:colour\`: the lamp's colour temperature, chosen as a
// camera's white balance would be: undyed ivory, at the centre of the lamp's pool, renders
// as L ${seen.L.toFixed(2)}, C ${seen.C.toFixed(3)}, h ${seen.h.toFixed(0)}°: its daylight colour plus a trace of the lamp's warmth.
export const LAMP_KELVIN = ${kelvin};
`);
console.log(`lamp: ${kelvin} K (${kelvinToHex(kelvin)}); ivory renders as L ${seen.L.toFixed(2)} C ${seen.C.toFixed(3)} h ${seen.h.toFixed(0)}°`);
console.log('wrote src/palette.calibrated.js');
