// Finds the phrases in the ney recordings (src/ney/*.mp3) for the ambience, and writes
// src/ney/phrases.js. Run: npm run find:phrases
//
// A phrase starts where the playing starts: the loudness, measured every 50 ms, jumps at
// least 15 dB above the quietest moment of the half second before it, and that moment was
// near-silence (30 dB under the loud parts): a pause, a breath, or the end of the last
// note's tail. Dips inside a phrase don't split it. It runs to the next start, cut where its
// tail has faded 35 dB under the loud parts. Each phrase also gets a gain that brings it
// to the same loudness as the others.
import { execFileSync } from 'child_process';
import { readdirSync, writeFileSync } from 'fs';

const SR = 16000, HOP = 0.05, RISE = 15, LOOK = 10, MIN_PHRASE = 2.5, TARGET_DB = -24;
const dir = new URL('../src/ney/', import.meta.url).pathname;
const db = v => 20 * Math.log10(Math.max(1e-9, v));
const out = [];
for (const f of readdirSync(dir).filter(f => f.endsWith('.mp3')).sort()) {
  const raw = execFileSync('ffmpeg', ['-v', 'error', '-i', dir + f, '-ac', '1', '-ar', String(SR), '-f', 'f32le', '-'], { maxBuffer: 1 << 28 });
  const x = new Float32Array(raw.buffer, raw.byteOffset, raw.byteLength / 4), hop = SR * HOP;
  const env = []; for (let i = 0; i + hop <= x.length; i += hop) { let s = 0; for (let j = i; j < i + hop; j++) s += x[j] * x[j]; env.push(db(Math.sqrt(s / hop))); }
  // loud: this recording's 90th percentile; quiet: 20 dB under it
  const loud = [...env].sort((a, b) => a - b)[Math.floor(env.length * 0.9)], quiet = loud - 20;
  const starts = [];
  for (let i = 1; i < env.length; i++) {
    const before = Math.min(...env.slice(Math.max(0, i - LOOK), i));
    if (env[i] > quiet && env[i] - before >= RISE && before < loud - 30 && (!starts.length || i - starts.at(-1) > LOOK)) starts.push(i);
  }
  const phrases = starts.map((a, k) => {
    let b = starts[k + 1] ?? env.length;
    while (b > a + 1 && env[b - 1] < loud - 35) b--;   // drop what's left of the tail
    return [a, b];
  });
  for (const [a, b] of phrases) {
    if ((b - a) * HOP < MIN_PHRASE) continue;
    let s = 0, n = 0; for (let i = a; i < b; i++) if (env[i] > quiet) { s += 10 ** (env[i] / 10); n++; }
    const level = 10 * Math.log10(s / n);
    // start a little early so the breath before the note stays
    out.push({ file: f, start: +Math.max(0, a * HOP - 0.15).toFixed(2), end: +Math.min(x.length / SR, b * HOP).toFixed(2), gain: +(10 ** ((TARGET_DB - level) / 20)).toFixed(3) });
  }
}
writeFileSync(dir + 'phrases.js', `// Generated by \`npm run find:phrases\`: the ney phrases the ambience plays (seconds), and
// the gain that brings each to the same loudness. Credits in src/ney/SOURCES.md.
export const PHRASES = ${JSON.stringify(out, null, 1).replace(/\n\s*/g, ' ')};
`);
for (const p of out) console.log(p.file.padEnd(26), String(p.start).padStart(6), '→', String(p.end).padStart(6), `${(p.end - p.start).toFixed(1)} s`, 'gain', p.gain);
